# Generated by Django 6.1.1 on 2026-10-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uom_master',
            fields=[
                ('uom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uom_code', models.CharField(max_length=20, unique=True)),
                ('uom_name', models.CharField(max_length=100)),
                ('uom_category', models.CharField(max_length=30)),
                ('decimal_places', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uom_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ref_item_uom_master',
                'ordering': ['uom_code'],
            },
        ),
    ]
